In [54]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [55]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [56]:
steps = [
    ("standard_scaler", StandardScaler()),
    ("classifier", LogisticRegression())
]

In [57]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [58]:
Pipe= Pipeline(steps)

In [59]:
from sklearn import set_config

In [60]:
set_config(display="diagram")

In [61]:
Pipe

,steps,"[('standard_scaler', ...), ('classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [62]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000)

In [63]:
X.shape

(1000, 20)

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [65]:
X_train

array([[-0.88819471,  1.43773562,  0.86376756, ..., -0.87611629,
        -1.02147299, -0.17800171],
       [-0.44198444,  1.65700248, -0.1184204 , ..., -1.2717102 ,
        -0.44572532,  0.51459877],
       [ 0.08013671,  0.28121487,  0.14037578, ...,  0.20457237,
        -0.92693496, -1.25705425],
       ...,
       [-0.7856551 , -0.66963456, -0.36319846, ...,  1.57855485,
         0.30777472, -0.36911593],
       [ 0.31217534,  1.62043424,  0.19094986, ..., -2.18724681,
        -0.48836224,  0.46552859],
       [ 0.32666798, -0.3476108 ,  1.0112489 , ...,  0.32796814,
         1.03719187, -0.26694464]], shape=(800, 20))

In [66]:
Pipe.fit(X_train,y_train)

,steps,"[('standard_scaler', ...), ('classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [67]:
Pipeline

sklearn.pipeline.Pipeline

In [68]:
y_pred=Pipe.predict(X_test)

In [69]:
y_pred

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0])

In [70]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [71]:

Pipe2 = Pipeline([
    ("scaling", StandardScaler()),
    ("PCA", PCA(n_components=3)),
    ("SVC", SVC())
])

In [72]:
pipeline = Pipeline(steps)

In [73]:
Pipe2.fit(X_train, y_train)


,steps,"[('scaling', ...), ('PCA', ...), ...]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,n_components,3
,copy,True
,whiten,False
,svd_solver,'auto'


In [74]:
Pipe2.predict(X_test)

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0])

In [75]:
from sklearn.impute import SimpleImputer


In [76]:
numeric_processor = Pipeline(
    steps=[
        ("imputation_mean", SimpleImputer(missing_values=np.nan, strategy="mean")),
        ("scaler", StandardScaler())
    ]
)

In [77]:
numeric_processor

,steps,"[('imputation_mean', ...), ('scaler', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'mean'
,fill_value,None
,copy,True
,add_indicator,False
,keep_empty_features,False
,copy,True


In [78]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

categorical_processor = Pipeline(
    steps=[
        ("imputation_constant", SimpleImputer(fill_value="missing", strategy='constant')),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)


In [79]:
categorical_processor

,steps,"[('imputation_constant', ...), ('onehot', ...)]"
,transform_input,None
,memory,None
,verbose,False
,missing_values,nan
,strategy,'constant'
,fill_value,'missing'
,copy,True
,add_indicator,False
,keep_empty_features,False
,categories,'auto'


In [80]:
from sklearn.compose import ColumnTransformer

In [81]:
preprocessors = ColumnTransformer(
    transformers=[
        ("categorical", categorical_processor, ["gender", "city"]),
        ("numerical", numeric_processor, ["age", "height"])
    ]
)

In [82]:
preprocessors

,transformers,"[('categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True
,force_int_remainder_cols,'deprecated'
,missing_values,nan
,strategy,'constant'
,fill_value,'missing'


In [83]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipe = make_pipeline(StandardScaler(), LogisticRegression())


In [84]:
pipe

,steps,"[('standardscaler', ...), ('logisticregression', ...)]"
,transform_input,None
,memory,None
,verbose,False
,copy,True
,with_mean,True
,with_std,True
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0


In [87]:
from sklearn.pipeline import make_pipeline

In [89]:
pipe=make_pipeline(LogisticRegression())


In [90]:
pipe

,steps,"[('logisticregression', ...)]"
,transform_input,None
,memory,None
,verbose,False
,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None


In [91]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

pipe = make_pipeline(preprocessors, LinearRegression())

In [92]:
pipe

,steps,"[('columntransformer', ...), ('linearregression', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('categorical', ...), ('numerical', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True
